<?php

namespace ZFT;

use Zend\Hydrator\ClassMethods;
use Zend\Hydrator\Strategy;

class CompositeHydrator extends ClassMethods {

    private $strategyNames = [];

    /**
     * @inheritDoc
     */
    public function addStrategy($name, Strategy\StrategyInterface $strategy) {
        $this->strategyNames[$name] = [];

        return parent::addStrategy($name, $strategy);
    }


    /**
     * @inheritDoc
     */
    public function hydrate(array $data, $object) {
        $keys = array_keys($data);

        foreach ($keys as $key) {
            $column = explode('_', $key, 2);
            $prefix = $column[0];
            if(! array_key_exists($prefix, $this->strategyNames)) continue;

            $this->strategyNames[$prefix][$column[1]] = $data[$key];
            unset($data[$key]);
        }

        $data = array_merge($data, $this->strategyNames);

        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

}
