<!-- Manual output of messages if need message type specific HTML (generic template will get in the way) -->
<!--<ul>-->
<?php
// $messages = $this->flashMessenger()->getPluginFlashMessenger()
//foreach ($messages as $message) : ?>
<!--    <li>--><?//= $message; ?><!--</li>-->
<?php //endforeach; ?>
<!--</ul>-->

PROFILE VIEW
<a href="<?= $this->url('profile/edit_profile/form_profile'); ?>">Edit</a>