<div class="row" id="adminUserGroups">
    <div class="col-md-3">

        <!-- Profile Image -->
        <div class="box box-primary">
            <div class="box-body box-profile">
                <img class="profile-user-img img-responsive img-circle" src="/img/user4-128x128.jpg" alt="User profile picture">

                <h3 class="profile-username text-center">Nina Mcintire</h3>

                <p class="text-muted text-center">Software Engineer</p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Closed tickets</b> <a class="pull-right">50</a>
                    </li>
                    <li class="list-group-item">
                        <b>Participations</b> <a class="pull-right">100</a>
                    </li>
                    <li class="list-group-item">
                        <b>Subscribers</b> <a class="pull-right">45</a>
                    </li>
                </ul>

                <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->

        <!-- About Me Box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">About Me</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>

                <p class="text-muted">Malibu, California</p>

                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>

                <p>
                    <span class="label label-danger">UI Design</span>
                    <span class="label label-success">Coding</span>
                    <span class="label label-info">Javascript</span>
                    <span class="label label-warning">PHP</span>
                    <span class="label label-primary">Node.js</span>
                </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>

                <p>Users who think they hate computers, actually hate bad programmers.</p>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-md-9">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li><a href="/admin/users/1/activity">Activity</a></li>
                <li><a href="/admin/users/1/timeline">Timeline</a></li>
                <li><a href="/admin/users/1/settings">Settings</a></li>
                <li class="active"><a href="#">Groups and Permissions</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="groups">
                    <select id='pre-selected-options' multiple='multiple'>
                        <option value='elem_1' selected>PHP Developer</option>
                        <option value='elem_2'>UI Design</option>
                        <option value='elem_3'>Admin</option>
                        <option value='elem_4' selected>Zend Framework Developer</option>
                        ...
                        <option value='elem_100'>elem 100</option>
                    </select>
                </div>
                <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>
        <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->
</div>
