<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo.png') ?>" alt="Zend Framework <?= \Portal\Module::VERSION ?>"/>&nbsp;Skeleton Application
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <?php
            echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_ERROR, array('alert', 'alert-danger'));

            echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_INFO, array('alert', 'alert-info'));

            echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_SUCCESS, array('alert', 'alert-success'));

            echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_WARNING, array('alert', 'alert-warning'));

            echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_DEFAULT, array('alert', 'alert-info'));
            ?>
            <?= $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
