<div class="box">
    <div class="box-header">
        <h3 class="box-title">Groups</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th><input type="checkbox" title="Все"/></th>
                <th>Name</th>
                <th>Direct descendants</th>
                <th>Total members</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td></td>
                <td><a href="/admin/groups/1/view">Admin</a></td>
                <td>1</td>
                <td>1</td>
            </tr>
            <tr>
                <td></td>
                <td>Users</td>
                <td>0</td>
                <td>12</td>
            </tr>
            <tr>
                <td></td>
                <td>Developers</td>
                <td>4</td>
                <td>10</td>
            </tr>
            <tr>
                <td></td>
                <td>PHP Developers</td>
                <td>3</td>
                <td>6</td>
            </tr>
            <tr>
                <td></td>
                <td>Zend Framework Developers</td>
                <td>3</td>
                <td>3</td>
            </tr>
            <tr>
                <td></td>
                <td>Designers</td>
                <td>2</td>
                <td>2</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
